# Generated by Django 5.2.16 on 2026-07-27 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(max_length=110, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "catégorie d'actualité",
                "verbose_name_plural": "catégories d'actualités",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=270, unique=True, verbose_name="slug"),
                ),
                ("excerpt", models.CharField(max_length=300, verbose_name="chapô")),
                ("body", models.TextField(verbose_name="contenu")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de publication",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.newscategory",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "actualités",
                "ordering": ["-published_at"],
            },
        ),
    ]
