# Generated by Django 5.2.16 on 2026-09-01 08:11

import apps.core.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=270, unique=True, verbose_name="slug"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("emploi", "Offre d'emploi"),
                            ("concours", "Concours"),
                        ],
                        default="emploi",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "organisme",
                    models.CharField(
                        help_text="Structure qui recrute ou organise le concours (ex. MINEFOP, CNFFDP, une délégation régionale).",
                        max_length=200,
                        verbose_name="organisme",
                    ),
                ),
                ("summary", models.CharField(max_length=300, verbose_name="résumé")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Diplômes, âge, expérience ou autres critères d'éligibilité.",
                        verbose_name="conditions de candidature",
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si l'offre reste ouverte jusqu'à nouvel ordre.",
                        null=True,
                        verbose_name="date limite de candidature",
                    ),
                ),
                (
                    "application_url",
                    models.URLField(blank=True, verbose_name="lien de candidature"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="courriel de contact"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Avis de concours ou fiche de poste, au format PDF.",
                        upload_to="opportunities/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            apps.core.validators.validate_file_size,
                        ],
                        verbose_name="avis officiel (PDF)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de publication",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
            ],
            options={
                "verbose_name": "opportunité",
                "verbose_name_plural": "opportunités & concours",
                "ordering": ["-published_at"],
            },
        ),
    ]
