# Generated by Django 5.2.16 on 2026-07-28 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="question")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="points"),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si la question admet plusieurs bonnes réponses (cases à cocher).",
                        verbose_name="plusieurs réponses correctes",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["quiz", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="consignes"),
                ),
                (
                    "pass_mark",
                    models.PositiveIntegerField(
                        default=50, verbose_name="note de passage (%)"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="durée limite (minutes)"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="0 = tentatives illimitées",
                        verbose_name="tentatives autorisées",
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quiz",
            },
        ),
        migrations.CreateModel(
            name="TrainingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(verbose_name="jour n°")),
                (
                    "date",
                    models.DateField(
                        help_text="Date à laquelle ce jour du programme s'ouvre aux candidats.",
                        verbose_name="date",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="titre du jour"),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, verbose_name="objectifs pédagogiques"),
                ),
            ],
            options={
                "verbose_name": "jour du programme",
                "verbose_name_plural": "emploi du temps",
                "ordering": ["program", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil candidat",
                "verbose_name_plural": "profils candidats",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="inscrit le"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.candidateprofile",
                        verbose_name="candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="texte")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="bonne réponse"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="training.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "choix de réponse",
                "verbose_name_plural": "choix de réponse",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="training.quiz",
                verbose_name="quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="commencé le"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="soumis le"
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="note (%)"),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="réussi")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="training.enrollment",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.quiz",
                        verbose_name="quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentative de quiz",
                "verbose_name_plural": "tentatives de quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="day",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="training.trainingday",
                verbose_name="jour",
            ),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Vidéo"),
                            ("link", "Lien externe"),
                            ("other", "Autre"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="training/materials/",
                        verbose_name="fichier",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="lien externe"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="mis en ligne le"
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="training.trainingday",
                        verbose_name="jour",
                    ),
                ),
            ],
            options={
                "verbose_name": "support de cours",
                "verbose_name_plural": "supports de cours",
                "ordering": ["day", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="intitulé")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=270, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("start_date", models.DateField(verbose_name="date de démarrage")),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="Code communiqué aux candidats pour rejoindre la formation. Généré automatiquement si laissé vide.",
                        max_length=12,
                        unique=True,
                        verbose_name="code d'accès",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Une formation non publiée n'apparaît pas dans le catalogue et refuse les inscriptions.",
                        verbose_name="publiée",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="structures.trainingcenter",
                        verbose_name="centre de formation",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_programs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="formateur responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "formation",
                "verbose_name_plural": "formations",
                "ordering": ["-start_date", "title"],
            },
        ),
        migrations.AddField(
            model_name="trainingday",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="training.trainingprogram",
                verbose_name="formation",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="training.trainingprogram",
                verbose_name="formation",
            ),
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="training.question",
                        verbose_name="question",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True,
                        to="training.choice",
                        verbose_name="choix sélectionnés",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="training.quizattempt",
                        verbose_name="tentative",
                    ),
                ),
            ],
            options={
                "verbose_name": "réponse",
                "verbose_name_plural": "réponses",
                "unique_together": {("attempt", "question")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="trainingday",
            unique_together={("program", "day_number")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("candidate", "program")},
        ),
    ]
