# Generated by Django 5.2.16 on 2026-07-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Avenue Winston Churchill, Yaoundé, Cameroun",
                        max_length=300,
                        verbose_name="adresse",
                    ),
                ),
                (
                    "po_box",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="boîte postale"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="contact@minefop.gov.cm",
                        max_length=254,
                        verbose_name="courriel",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        default="Lundi – Vendredi : 7h30 – 15h30",
                        max_length=200,
                        verbose_name="horaires d'ouverture",
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True, verbose_name="URL de la carte (iframe)"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="X (Twitter)"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
            ],
            options={
                "verbose_name": "informations de contact",
                "verbose_name_plural": "informations de contact",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom complet")),
                ("email", models.EmailField(max_length=254, verbose_name="courriel")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="objet")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'envoi"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
            ],
            options={
                "verbose_name": "message de contact",
                "verbose_name_plural": "messages de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
