# Generated by Django 5.2.16 on 2026-07-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="sous-titre"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hero/", verbose_name="image"
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="libellé du lien"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="URL du lien"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "diapositive d'accueil",
                "verbose_name_plural": "diapositives d'accueil",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="KeyFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=150, verbose_name="libellé")),
                ("value", models.CharField(max_length=50, verbose_name="valeur")),
                (
                    "icon",
                    models.CharField(
                        default="bi-bar-chart-fill",
                        max_length=50,
                        verbose_name="icône (bootstrap-icons)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "chiffre clé",
                "verbose_name_plural": "chiffres clés",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MinisterMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="À renseigner par le Ministère avec le nom officiel du Ministre en exercice.",
                        max_length=200,
                        verbose_name="nom complet",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ministre de l'Emploi et de la Formation Professionnelle",
                        max_length=200,
                        verbose_name="titre / fonction",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cabinet/",
                        verbose_name="photo",
                    ),
                ),
                ("message", models.TextField(verbose_name="mot du ministre")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "mot du ministre",
                "verbose_name_plural": "mot du ministre",
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10, verbose_name="année")),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "étape historique",
                "verbose_name_plural": "historique",
                "ordering": ["order", "year"],
            },
        ),
    ]
