# Generated by Django 5.2.16 on 2026-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="nom")),
                (
                    "acronym",
                    models.CharField(
                        blank=True,
                        help_text="Affiché en vignette lorsque aucun logo n'est téléversé.",
                        max_length=30,
                        verbose_name="sigle",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("institution", "Institutions de la République"),
                            ("partner", "Organismes, projets et partenaires"),
                            ("service", "Services et plateformes en ligne"),
                        ],
                        default="partner",
                        max_length=20,
                        verbose_name="rubrique",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Laisser vide pour une structure dont le site n'est pas encore publié.",
                        max_length=300,
                        verbose_name="adresse du site",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/",
                        verbose_name="logo",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="affiché sur le portail"
                    ),
                ),
            ],
            options={
                "verbose_name": "site partenaire",
                "verbose_name_plural": "sites partenaires",
                "ordering": ["group", "order", "name"],
            },
        ),
    ]
