# Generated by Django 5.2.16 on 2026-08-31 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_partnersite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnersite",
            options={
                "ordering": ["column", "order", "name"],
                "verbose_name": "site partenaire",
                "verbose_name_plural": "sites partenaires",
            },
        ),
        migrations.AddField(
            model_name="partnersite",
            name="column",
            field=models.CharField(
                choices=[("left", "Colonne de gauche"), ("right", "Colonne de droite")],
                default="left",
                help_text="Côté du portail où la vignette est placée.",
                max_length=10,
                verbose_name="colonne",
            ),
        ),
        migrations.AddField(
            model_name="partnersite",
            name="tint",
            field=models.CharField(
                blank=True,
                help_text="Couleur du bandeau qui porte le nom de la structure, au survol de la vignette. Ex : #27ae60. Laisser vide pour le fond sombre par défaut.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$",
                        "Indiquez une couleur hexadécimale, par exemple #27ae60.",
                    )
                ],
                verbose_name="couleur du bandeau",
            ),
        ),
    ]
