# Generated by Django 5.2.16 on 2026-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_partner_site_portal_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnersite",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="Adresse du logo fourni par la structure, utilisée tant qu'aucun fichier n'a été téléversé ci-dessus. La commande « fetch_partner_logos » récupère ces images et les héberge sur le domaine du Ministère.",
                max_length=500,
                verbose_name="adresse du logo",
            ),
        ),
    ]
