# Generated by Django 5.2.16 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_minister_message_style_rewrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministermessage",
            name="biography_en",
            field=models.TextField(blank=True, verbose_name="biographie (anglais)"),
        ),
        migrations.AddField(
            model_name="ministermessage",
            name="biography_fr",
            field=models.TextField(blank=True, verbose_name="biographie (français)"),
        ),
    ]
