# Generated by Django 5.2.16 on 2026-07-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(max_length=110, unique=True, verbose_name="slug"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "catégorie de document",
                "verbose_name_plural": "catégories de documents",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Ex : Loi n° 2018/010 du 11 juillet 2018",
                        max_length=150,
                        verbose_name="référence",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/", verbose_name="fichier PDF"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date de signature/publication",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-published_date", "title"],
            },
        ),
    ]
