# Generated by Django 5.2.16 on 2026-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="À utiliser lorsque le document n'a pas encore été téléversé et reste hébergé à son adresse d'origine. Le fichier téléversé prévaut.",
                max_length=500,
                verbose_name="adresse du fichier",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, upload_to="documents/", verbose_name="fichier PDF"
            ),
        ),
    ]
