# Generated by Django 5.2.16 on 2026-08-31 22:25

import apps.blog.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=270, unique=True, verbose_name="slug"),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Nom affiché publiquement comme auteur de l'article (personne, service ou cellule de communication).",
                        max_length=150,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Court résumé affiché dans la liste des articles.",
                        max_length=300,
                        verbose_name="chapô",
                    ),
                ),
                ("body", models.TextField(verbose_name="contenu")),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Image mise en avant en tête d'article et dans la liste du blog.",
                        upload_to="blog/covers/",
                        validators=[apps.blog.validators.validate_file_size],
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de publication",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Compte de l'espace d'administration ayant créé l'article — distinct du nom d'auteur affiché publiquement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "article de blog",
                "verbose_name_plural": "articles de blog",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="blog/attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                ]
                            ),
                            apps.blog.validators.validate_file_size,
                        ],
                        verbose_name="document",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Affiché à la place du nom de fichier ; laisser vide pour l'utiliser tel quel.",
                        max_length=200,
                        verbose_name="titre du document",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="blog.blogpost",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "document joint",
                "verbose_name_plural": "documents joints",
                "ordering": ["order", "id"],
            },
        ),
    ]
