# Generated by Django 5.2.16 on 2026-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_bilingual_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="scope",
            field=models.CharField(
                choices=[("national", "National"), ("regional", "Régional")],
                default="national",
                max_length=10,
                verbose_name="portée",
            ),
        ),
    ]
