# Generated by Django 5.2.16 on 2026-07-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttachedBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="nom")),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=30, verbose_name="sigle"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("website", models.URLField(blank=True, verbose_name="site web")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "organisme rattaché",
                "verbose_name_plural": "organismes rattachés",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                ("capital", models.CharField(max_length=100, verbose_name="chef-lieu")),
            ],
            options={
                "verbose_name": "région",
                "verbose_name_plural": "régions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="nom")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("cabinet", "Cabinet du Ministre"),
                            ("inspection", "Inspection Générale"),
                            ("division", "Division"),
                            ("direction", "Direction"),
                            ("sous_direction", "Sous-direction"),
                            ("cellule", "Cellule"),
                            ("service", "Service"),
                            ("bureau", "Bureau"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "head_title",
                    models.CharField(
                        blank=True,
                        help_text="Ex : Chef de Division",
                        max_length=150,
                        verbose_name="responsable",
                    ),
                ),
                ("mission", models.TextField(blank=True, verbose_name="attributions")),
                (
                    "legal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ex : Article 25",
                        max_length=100,
                        verbose_name="référence légale",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="structures.orgunit",
                        verbose_name="unité parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "unité organisationnelle",
                "verbose_name_plural": "organigramme",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("regional", "Délégation Régionale"),
                            ("departmental", "Délégation Départementale"),
                        ],
                        max_length=20,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="département"
                    ),
                ),
                ("town", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="courriel"
                    ),
                ),
                (
                    "delegate_name",
                    models.CharField(
                        blank=True,
                        help_text="À renseigner par le Ministère.",
                        max_length=150,
                        verbose_name="délégué(e)",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="structures.region",
                        verbose_name="région",
                    ),
                ),
            ],
            options={
                "verbose_name": "délégation",
                "verbose_name_plural": "délégations",
                "ordering": ["region__name", "department_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="nom")),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            (
                                "cfpe",
                                "Centre de Formation Professionnelle d'Excellence (CFPE)",
                            ),
                            (
                                "csfp",
                                "Centre Sectoriel de Formation Professionnelle (CSFP)",
                            ),
                            ("cfm", "Centre de Formation aux Métiers (CFM)"),
                            ("cap", "Centre d'Apprentissage Professionnel (CAP)"),
                            (
                                "cpfpr",
                                "Centre Public de Formation Professionnelle Rapide (CPFPR)",
                            ),
                            (
                                "sarsm",
                                "Section Artisanale Rurale / Section Ménagère (SAR/SM)",
                            ),
                            (
                                "cnffdp",
                                "Centre National de Formation des Formateurs et de Développement des Programmes",
                            ),
                            ("private", "Centre privé agréé"),
                        ],
                        max_length=20,
                        verbose_name="type de centre",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="structure publique"
                    ),
                ),
                ("town", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="courriel"
                    ),
                ),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Liste séparée par des virgules",
                        verbose_name="filières de formation",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_centers",
                        to="structures.region",
                        verbose_name="région",
                    ),
                ),
            ],
            options={
                "verbose_name": "centre de formation",
                "verbose_name_plural": "centres de formation",
                "ordering": ["region__name", "town", "name"],
            },
        ),
    ]
