# Generated by Django 5.2.16 on 2026-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachedbody",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "organisme, programme ou projet",
                "verbose_name_plural": "organismes, programmes et projets",
            },
        ),
        migrations.AddField(
            model_name="attachedbody",
            name="kind",
            field=models.CharField(
                choices=[
                    ("body", "Organisme rattaché"),
                    ("programme", "Programme ou projet"),
                ],
                default="body",
                max_length=20,
                verbose_name="nature",
            ),
        ),
    ]
