# Generated by Django 5.2.16 on 2026-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0002_alter_attachedbody_options_attachedbody_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="director_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="courriel du responsable"
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="director_name",
            field=models.CharField(
                blank=True,
                help_text="Nom de la personne occupant actuellement ce poste — à tenir à jour par le Ministère.",
                max_length=150,
                verbose_name="nom du responsable actuel",
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Généré automatiquement pour les directions ; sert à leur page dédiée.",
                max_length=270,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
