# Generated by Django 5.2.16 on 2026-09-02 07:44

from django.db import migrations, models

# Maps each existing CenterType to the new browse/filter Category for public
# centres, so the directory's category filter works immediately on an
# already-seeded database, not just on fresh installs.
CATEGORY_BY_CENTER_TYPE = {
    "cnffdp": "national",
    "cfpe": "regional",
    "csfp": "reference",
    "cpfpr": "divisional",
    "cfm": "divisional",
    "cap": "divisional",
    "sarsm": "sarsm",
}


def backfill_category(apps, schema_editor):
    TrainingCenter = apps.get_model("structures", "TrainingCenter")
    for center_type, category in CATEGORY_BY_CENTER_TYPE.items():
        TrainingCenter.objects.filter(center_type=center_type, category="").update(category=category)


def clear_category(apps, schema_editor):
    TrainingCenter = apps.get_model("structures", "TrainingCenter")
    TrainingCenter.objects.update(category="")


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0006_seed_divisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcenter",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "Centre national"),
                    ("regional", "Centre régional"),
                    ("reference", "Centre de référence"),
                    ("divisional", "Centre divisionnaire"),
                    ("sarsm", "SAR/SM"),
                ],
                help_text="Structures publiques uniquement — sert au filtrage de l'annuaire.",
                max_length=20,
                verbose_name="catégorie",
            ),
        ),
        migrations.AddField(
            model_name="trainingcenter",
            name="division",
            field=models.CharField(
                blank=True,
                help_text="Structures privées uniquement — sert au filtrage de l'annuaire par division.",
                max_length=100,
                verbose_name="division",
            ),
        ),
        migrations.RunPython(backfill_category, clear_category),
    ]
