# Generated by Django 5.2.16 on 2026-09-01 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=270, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "location",
                    models.CharField(blank=True, max_length=250, verbose_name="lieu"),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date et heure de début",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date et heure de fin"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="events/",
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
            ],
            options={
                "verbose_name": "événement",
                "verbose_name_plural": "événements",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="légende"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="photo"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ajoutée le"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="site_media.event",
                        verbose_name="événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "galerie photo",
                "ordering": ["order", "-uploaded_at"],
            },
        ),
    ]
